---
- hosts: 172.31.61.167
  vars:
  - warName: java-example.war
  - warRemotePath: /opt/apache-tomcat9/webapps/

  tasks:
  - name: Copy WAR to Remote server
    copy: src=target/{{ warName }} dest={{ warRemotePath }}/{{ warName }} owner=manager-gui group=tomcat
   
